apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-portfolio
  template:
    metadata:
      labels:
        app: personal-portfolio
    spec:
      containers:
      - name: personal-portfolio
        image: personalportfolio.azurecr.io/personal-portfolio:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret